---Used internally.
---
---If you want to annotate a config passed to `setup()`,
---then `spotlight.ConfigPartial` is a better choice.
---@class (exact) spotlight.Config
---@field count boolean
---@field hl_group string

---@class (exact) spotlight.ConfigPartial
---@field count? boolean
---@field hl_group? string
